name: Build Server Image
on:
  push:
    branches: ["master"]
jobs:
  deploy_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt-hotspot
          cache: maven
      - name: Build with Maven
        run: mvn clean -U package -Pproduction -pl server
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker deploy
        uses: docker/build-push-action@v3
        with:
          push: true
          context: server/
          tags: |
            ghcr.io/waterdogpe/flow-assets-server:latest